### ISSUE TITLE
Heroku Issue: ActionView::Template::Error (The asset "tailwind.css" is not present in the asset pipeline.")

### ISSUE THREAD

**Issue by Dnncha** [rails/tailwindcss-rails#153]
Hi

Thanks for your work. 

I'm running a very simple Rails 7.0.2.2 which I've just set up. 

Everything is working swimmingly locally, but when I deploy to heroku I'm getting the following error when I try to view a page:

ActionView::Template::Error (The asset "tailwind.css" is not present in the asset pipeline.)

I have checked to ensure that sassc-rails is disabled in the Gemfile. 

I have also tried adding 

config.assets.css_compressor = nil

to production.rb, but the error remains.

Any ideas where I am going wrong?

Thanks

**Comment by joao99c** [comment]
I fixed this problem running:
`gem install bundler`
`bundle update --bundler`
`bundle lock --add-platform x86_64-linux`

Hope it helps!
JC

**Comment by peteoliveira** [comment]
I am seeing the same issue when running tests on github.
config.assets.css_compressor = nil did not work and x86_64-linux is already present in Gemfile.lock

> 1) Recordings GET /new returns http success
     Failure/Error: <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
     ActionView::Template::Error:
The asset "tailwind.css" is not present in the asset pipeline.
./app/views/layouts/application.html.erb:12:in `_app_views_layouts_application_html_erb__1997779[47](https://github.com/nuance-internal/sphere-enterprise/runs/5434230804?check_suite_focus=true#step:6:47)84[49](https://github.com/nuance-internal/sphere-enterprise/runs/5434230804?check_suite_focus=true#step:6:49)135196_69[50](https://github.com/nuance-internal/sphere-enterprise/runs/5434230804?check_suite_focus=true#step:6:50)0'
./spec/requests/recordings_spec.rb:6:in `block (3 levels) in <main>'
--- Caused by: ---
Sprockets::Rails::Helper::AssetNotFound:
The asset "tailwind.css" is not present in the asset pipeline.
./app/views/layouts/application.html.erb:12:in `_app_views_layouts_application_html_erb__199777947844913[51](https://github.com/nuance-internal/sphere-enterprise/runs/5434230804?check_suite_focus=true#step:6:51)96_69500'

**Comment by dmarcoux** [comment]
@peteoliveira: If you have this issue while running tests in your continuous integration, you need to precompile assets with:

```bash
bundle exec rake assets:precompile
```

I had the same issue and this fixed it.

**Comment by peteoliveira** [comment]
@dmarcoux That worked, thanks!

**Comment by ur5us** [comment]
@dmarcoux Shouldn’t CI be handled by the Rake tasks?

```ruby
Rake::Task["assets:precompile"].enhance(["tailwindcss:build"])

if Rake::Task.task_defined?("test:prepare")
  Rake::Task["test:prepare"].enhance(["tailwindcss:build"])
elsif Rake::Task.task_defined?("db:test:prepare")
  Rake::Task["db:test:prepare"].enhance(["tailwindcss:build"])
end
```

Having said that, I’m having the same issue in CircleCI. I call `bin/rails db:test:prepare` explicitly before running RSpec but that `tailwindcss:build` task is never executed. Am I misunderstanding those `*test:prepare` enhancements?

**Comment by dmarcoux** [comment]
I didn't know about those enhancements. I prepare my test database with `bundle exec rake db:reset`. I'll give `bundle exec rake db:test:prepare` a try. It should build Tailwind CSS assets before preparing the test databse. This sounds exactly like what we need.

**Comment by ur5us** [comment]
@dmarcoux 

> Edit: After giving the rake task db:test:prepare a try, it's not calling the rake task tailwindcss:build. I don't know why, because this should happen.

Yeah, this is exactly what I’m seeing also as mentioned:

> I call bin/rails db:test:prepare explicitly before running RSpec but that tailwindcss:build task is never executed.

Maybe @flavorjones or @dhh can shine some light?

**Comment by elgrillo83** [comment]
Similar things are happening to me after updating the `tailwindcss-rails` gem from `2.0.5` to `2.0.8`:
```
# Excerpt from my `Gemfile.lock`:

rails (7.0.2.3)

- tailwindcss-rails (2.0.5-arm64-darwin)
+ tailwindcss-rails (2.0.8-arm64-darwin)

RUBY VERSION
   ruby 3.0.3p157

BUNDLED WITH
   2.2.32
``` 
The tests run by GitHub CI were then failing with:
```
ActionView::Template::Error: couldn't find file 'tailwind.css'
``` 

After re-reading https://github.com/rails/tailwindcss-rails#building-for-testing, I was able to fix that by adapting the run script: 
```
# Excerpt from my `.github/workflows/ci.yml`:

- run: bin/rake test
+ run: bin/rake test:all
``` 

Not running `rake db:test:prepare` though, just `rake db:setup`.

**Comment by Timmitry** [comment]
I also suddenly had this problem after upgrading `tailwindcss-rails` from 2.0.5 to 2.0.10.

The problem is present both locally (after removing old assets with `bin/rails assets:clobber`) and on the continuous integration.

I solved it by adding the following to my system test configuration:

```ruby
# spec/support/system_test_configuration.rb
# Could alternatively be added to `rails_helper.rb` or `spec_helper.rb`
RSpec.configure do |config|
  ...

  config.before(:suite) do
    Rails.application.load_tasks
    Rake::Task["tailwindcss:build"].invoke
  end
end
```

Works like a charm. Still seems like a breaking change in a patch version, though 😉

**Comment by ionmx** [comment]
@dmarcoux Great! it works like a charm... I'm using the Ruby On Rails CI provided by GitHub Actions, I added the assets precompile before running the tests.

```
...
# Precompile assets
- name: Assets Precompile
  run: bundle exec rake assets:precompile
# Add or replace test runners here
- name: Run tests
  run: bin/rake
...
```

**Comment by gabrielboeker** [comment]
none of the suggested solutions work for me which is really frustrating since my productive env is broken right now... staging works fine though.

**Comment by seanbjornsson** [comment]
`tailwindcss:build` was not sufficient for me to fix this issue. I have to run `precompile:assets` to resolve this.

**Comment by hendricius** [comment]
> /app/assets/builds/*

Wouldn't that mean that you have to commit your assets all the time?

**Comment by noahd1** [comment]
For me, it was helpful to see which tasks tailwindcss-rails hooks into. You can see that here:

https://github.com/rails/tailwindcss-rails/blob/main/lib/tasks/build.rake#L15-L21

If you're using RSpec, you need to figure out a way to build tailwind's CSS or you'll receive this error. 

@Timmitry 's solution worked for me in this case. I also put the whole block in a `unless ENV["CI"]` because CI precompiles assets, which in turn, as per the task definition, builds tailwind as well. Otherwise, tailwind would be built more than once (not the end of the world but simple to avoid).

**Comment by flavorjones** [comment]
If someone on this thread would be willing to submit a documentation PR to update the README, I would be very grateful!

**Comment by LoranKloeze** [comment]
Posting the following since this issue turns up as the first result on Google when searching for _(The asset "tailwind.css" is not present in the asset pipeline_.

For the scenario where you use **Docker** and where you have **precompiled assets locally**, don't forget to remove the same lines in `.dockerignore` as you removed them in `.gitignore`. E.g. 

**.dockerignore**
```
.git
tmp
!tmp/pids
log
public/assets <-- remove/comment out this line
public/packs
.bundle

db/*.sqlite3
db/*.sqlite3-*

storage
config/master.key
config/credentials/*.key

node_modules
```

**Comment by Zuhaib042** [comment]
> none of the suggested solutions work for me which is really frustrating since my productive env is broken right now... staging works fine though.
> 
> Edit: Turns out in my gitignore i had `/app/assets/builds/*` which caused this issue... commenting out the line did the trick. weird.
Thank you so much man, I was in deep trouble and spent hours fixing this `tailwind asset pipeline` issue while deploying rails app on render.
I actually noticed that .gitignore has this `/app/assets/builds/*` and then when I found out your solution then I went away with it and solved it.

**Comment by olivierlacan** [comment]
For the goofballs like me who don't notice a compilation error and only notice the failure to precompile `tailwind.css` I strongly recommend checking our CI output for a `CssSyntaxError` caused by (for example) usage of a non-existent CSS class with `@apply`. 

Since this happened in my `Setup test database` stage and (annoyingly) didn't result in a `1` exit code (which would be best IMO, but may not be straightforward to achieve), I **assumed** wrongly that something had indeed failed to precompile `tailwind.css` despite my correct usage of `db:test:prepare` in my setup. 

Nope, turned out I derped and Tailwind errored when trying to compile my typo, but then it failed to compile — as you'd expect. 

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/65950/233516543-1859bf1c-a9ac-4976-a7b0-b7b37a27120d.png">

**Comment by fwuensche** [comment]
I can confirm that two of the previously suggested solutions work for me. 

**Run all tests at once with `bundle exec rails test:all`**

- https://github.com/cherrypush/cherry/pull/80/commits/808817525e55738928fdc7b65bdf9c3432699e6c

**Explicitly precompile assets before running your tests**

- https://github.com/cherrypush/cherry/pull/80/commits/3967c6eabfa9a5fd6f2d233f25fa56c9cd4020da

I'm sticking to the second solution, so I can keep unit tests separated from system tests. 

You can check the builds on the two last commits of this pull request: https://github.com/cherrypush/cherry/pull/80

Hope that helps ❤️

**Comment by kevin-dapps** [comment]
I'm running into an issue with running `tailwindcss-rails` gem in staging on heroku. I'm using the container stack (Docker) and keep getting the following error
`ActionView::Template::Error (The asset "tailwind.css" is not present in the asset pipeline.)`

This issue is closed, and I've done all of the following:

 -Made sure config.assets.css_compressor = nil
-Remove sassc-rails gem from Gemfile  (I didn't have it in mine)
-I tried going on Heroku and running bundle exec rake assets:precompile and it compiles the assets and generates the manifest file but still get the same error even though it builds and places the generated assets into the public/assets folder correctly. I'm wondering if I for some reason need to do something different since I'm deploying using Docker
I've tried setting `config.assets.compile = true` in my `staging.rb` to enabled live compilation on staging but that doesn't appear to work either.
I've tried running it locally using `RAILS_ENV=staging rails s` and I receive the same error except after running the `rails assets:precompile` locally it works as expected.

I've tried everything listed in this GitHub issue and still can't get it work. Any help is truly appreciated

**Comment by kalashnikovisme** [comment]
Running `assets:precompile` in CI for this purpose looks like an overhead.

Enhancing prepare commands with `tailwindcss:build` is the good idea and it's already implemented [here](https://github.com/rails/tailwindcss-rails/blob/e333322623cdc8ebbe953222cd7e064fe6b49e23/lib/tasks/build.rake#L23-L29)

```ruby
if Rake::Task.task_defined?("test:prepare")
  Rake::Task["test:prepare"].enhance(["tailwindcss:build"])
elsif Rake::Task.task_defined?("spec:prepare")
  Rake::Task["spec:prepare"].enhance(["tailwindcss:build"])
elsif Rake::Task.task_defined?("db:test:prepare")
  Rake::Task["db:test:prepare"].enhance(["tailwindcss:build"])
end
```

So, you can just add `bin/rake spec:prepare` for RSpec tests, for example :slightly_smiling_face:

**Comment by pas256** [comment]
What does `rake spec:prepare` do? It isn't listed when I run `rake -T` but somehow it still works and fixed my tests in CI (GitHub Actions). Thanks @kalashnikovisme

**Comment by fernandokosh** [comment]
I only makethis working after run:

 `rake tailwindcss:build`

**Comment by andrew** [comment]
My fix for this error was to make sure that the app/assets/builds directory is in git:

`git add app/assets/builds.keep -f`

**Comment by sebastialonso** [comment]
I'm experiencing this issue in production, even though I've already run or have these:

* `rake assets:precompile` already runs `tailwindcss:build`
* `apps/assets/builds` already contains a `.keep` and also a `tailwind.css`

Always getting 
~~~
Sprockets::Rails::Helper::AssetNotFound (The asset "tailwind.css" is not present in the asset pipeline.
~~~

Anybody managed to solve this?

**Comment by aksafan** [comment]
> ~`tailwindcss:build` was not sufficient for me to fix this issue. I have to run `precompile:assets` to resolve this.~ Edit: I spoke too soon. This resolves the issue locally but not on Gitlab CI
> 
> What ended up working:
> 
> ```ruby
> # config/application.rb
> config.assets.css_compressor = nil
> ```

The only thing that worked for me is adding `Rails.application.config.assets.css_compressor = nil` to initializers/assets.rb and I've tried everything from this thread and even more from the Internet.

Thanks for the help @seanbjornsson!

**Comment by aksafan** [comment]
> > none of the suggested solutions work for me which is really frustrating since my productive env is broken right now... staging works fine though.
> > Edit: Turns out in my gitignore i had `/app/assets/builds/*` which caused this issue... commenting out the line did the trick. weird.
> 
> > /app/assets/builds/*
> 
> @gabrielboeker Wouldn't that mean that you have to commit your assets all the time?

Oh, I thought I got some kind of glitch or smth, cause I've just baked a sourdough bread by your recipe @hendricius and now I see you here answering about the Ruby. What a great coincidence!

**Comment by jeffdill2** [comment]
For those who have mentioned removing `/app/assets/builds/*` from their `.gitignore` file, I'd recommend doing this instead of removing that line entirely:

```bash
/app/assets/builds/*
!/app/assets/builds/.keep
```

This will ignore ignore anything in the `/builds` directory _except for_ the `.keep` file.

**Comment by bilalhussain-dev** [comment]
> [@peteoliveira](https://github.com/peteoliveira): If you have this issue while running tests in your continuous integration, you need to precompile assets with:
> 
> bundle exec rake assets:precompile
> I had the same issue and this fixed it.

Love it! Problem solved!
