### ISSUE TITLE
Warning "Unrecognized at-rule or error parsing at-rule ‘@tailwind’." in clean install

### ISSUE THREAD

**Issue by febeling** [rails/tailwindcss-rails#190]
When starting a new rails 7 app and adding, then installing, tailwindcss-rails, and adding a single route using layout, the resulting page will produce this warning in the browser console:
```
Unrecognized at-rule or error parsing at-rule ‘@tailwind’.
```
The `@tailwind` at-rule should obviously not be in the processed output.

It still is, because the standard `app/assets/stylesheets/application.css` file contains the `= require_tree .` directive. This way, while the tailwind preprocessing does handle everything correctly, in addition the `application.tailwind.css` file is processed in the asset pipeline. It is concatenated into the fingerprinted application.css verbatim.

It does little damage, because all styles are working, but it's confusing and dirty. It might be obvious for many, but the docs for installation could use a note to change a possibly existing default `application.css` manifest.

Rails 7.0.3.1
tailwindcss-rails 2.0.12

**Comment by bdevel** [comment]
I've found this as well, which caused a lot of confusion. This behavior also prevents you from using `require_tree .` because you can't exclude the `application.tailwind.css` file.

For context:

The default `app/assets/stylesheets/application.css`has:
```
/*
 *= require_tree .
 *= require_self
 */
```

Which includes `app/assets/stylesheets/application.tailwind.css`:

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

On build, it just copies the `application.tailwind.css` verbatim into the built `/assets/application-{CHECKSUM}.css` file.

**Comment by flavorjones** [comment]
I would welcome a PR with an update to the README's "Troubleshooting" section.

**Comment by febeling** [comment]
@flavorjones You think this would do?
