### ISSUE TITLE
Tailwind scaffold template is out of sync with rails/rails ERB scaffold template

### ISSUE THREAD

**Issue by yshmarov** [rails/tailwindcss-rails#341]
https://github.com/rails/tailwindcss-rails/blob/main/lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt is out of sync with https://github.com/rails/rails/blob/main/railties/lib/rails/generators/erb/scaffold/templates/index.html.erb.tt, namely it's missing the `<% content_for :title, "New event" %>`

Should template files be kept in sync (except the tailwind classes)?

<img width="941" alt="Screenshot 2024-03-24 at 21 55 11" src="https://github.com/rails/tailwindcss-rails/assets/13472945/3e010c0a-3f99-414d-b4b0-5e5ede4b6f0a">

**Comment by flavorjones** [comment]
@yshmarov Thanks for spotting that! If you have the time to submit a PR I would be happy to merge it. If not, please let me know and I can fix it later this week.

**Comment by flavorjones** [comment]
Looking at the changes to rails templates since 2021, there are a few changes that should probably be carried over to this gem. I'm not going to do this work, but would welcome anyone from the community who would like to submit a PR.

I _think_ the set of changes that should be looked at is limited to:

- rails/rails#43611 (rails/rails@6cd75a42)
- rails/rails#43846 (rails/rails@1c390905)
- rails/rails#43880 (rails/rails@ea15f8e6)
- rails/rails#49702 (rails/rails@42ca4de4)
