### ISSUE TITLE
Purge also purges other stylesheets

### ISSUE THREAD

**Issue by stephenson** [rails/tailwindcss-rails#5]
I have [Administrate](https://github.com/thoughtbot/administrate) installed, and the tailwdindcss-rails gem seems to also purge the CSS of Administrate. Seems like there is some kind of scoping needed to keep the purging to the tailwind css file.

Administrate.css without purge: https://gist.github.com/stephenson/6384c02f8645ae5d9977f3e1182935d4
Administrate.css with purge: https://gist.github.com/stephenson/284a7a93c87da5271684c95831e0eb1d

Any tricks or tips to fix? Would love to contribute, but sadly don't know where to start.

Let me know if there is anything I can do, if needed you can get access to the repo :)

**Comment by kaspth** [comment]
👋, haven't used Administrate but I'm guessing it's a Rails::Engine, so those views aren't considered, so the compressor would need to be told to look at those view files via something like:

```ruby
config.assets.css_compressor = Tailwindcss::Compressor.new(files_with_class_names: Rails.root.glob("some/engine/root/**/*.*"))
```

(I don't know where to find the engine root though, depends on the gem install.)

But seems tailwindcss-rails should be Rails::Engine aware and the default `app/views` and `app/helpers` directories shouldn't be tied to just `Rails.root` necessarily. Can't remember how Rails::Engines automatically add their views to the main Rails app, but when we find that, I think we can reuse that to siphon extra locations to look.

**Comment by stephenson** [comment]
Yeah, I think it's a good solution to make et engine aware. Just as a side note: There is stuff in the administrate.css file after purge because I have generated some of the Administrate views in the app/views folder.

I will go hunting for the path to the Administrate views :)

**Comment by dhh** [comment]
Hmm, yeah, that's a good issue. Probably need some way for the compressor to only apply to certain files. I'll have a look at that. And also, we need to document how to include the engine views to consider those – because that might well be relevant for Tailwind too, if you use that in your engines.

**Comment by Bramjetten** [comment]
We've added Tailwind to our Rails engine (without webpacker) by [compiling a custom build using npx](https://github.com/Bramjetten/Spina/blob/hotwire/lib/tasks/spina_tasks.rake) that gets imported by Sprockets. It'd be great if instead of using `npx` to purge unnecessary classes, we could use this Purger to target our Tailwind build specifically (and skip the main app's stylesheets). I believe (as discussed in #1) it's better to do this in a separate gem though.

**Comment by stephenson** [comment]
> Hmm, yeah, that's a good issue. Probably need some way for the compressor to only apply to certain files. I'll have a look at that. And also, we need to document how to include the engine views to consider those – because that might well be relevant for Tailwind too, if you use that in your engines.

I think a good start would be to have an option to only purge Tailwind as it's already a separate file, which would make it less intrusive.

I am also a big fan of a general purger gem.

**Comment by stephenson** [comment]
The fix works great, thanks 🥰
